myQueue = [] 
myQueue.append('data science') 
myQueue.append('data analytics')
myQueue.append('data structures and algorithms')
myQueue.append('big data')
myQueue.append('learning data analytics')
print(myQueue)
print(myQueue.pop(0)) 
print(myQueue.pop(0))
print(myQueue)